FROM node:12

WORKDIR /usr/app/server

COPY package*.json ./

RUN npm install

RUN git clone https://github.com/vishnubob/wait-for-it.git

COPY . .

CMD ["./wait-for-it/wait-for-it.sh", "mysql:3306","--timeout=30", "--", "npm", "run", "docker"]

# CMD ["npm","run","docker"]