# This is a basic workflow to help you get started with Actions

name: CI-SERVER

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [master, staging] # if github changes the 'master' to 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.17
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: spotify_orm_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node  (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Server dependencies
        run: npm ci
        working-directory: ./server
      - name: create DB and migrate, the play test
        run: |
          npm run initDB &&
          npm run migrateTest &&
          npm run test
        env:
          NODE_ENV: "test"
          DB_TEST: "spotify_orm_test"
          IP_ADDRESS: "http://localhost:3000"
          DB_HOST: "127.0.0.1"
          REFRESH_TOKEN_SECRET: nvsa2jhb54vjm253lvhmk25hvk3mx9mv5wgv5wvx8239
          ACCESS_TOKEN_SECRET: jkslk436236243643523dfdgfgfv522n5gnkl25guc0x2
          EMAIL_TOKEN_SECRET: alhdfgvhalngycadfvadfbafbadsfvd256vl52lkv5fmldh
        working-directory: ./server
